### ISSUE TITLE
Add cooldown between bonfire right-clicks

### ISSUE THREAD

**Issue by Norazan** [MineInAbyss/Bonfire#13]
Spamclicking a bonfire drops TPS pretty easily right now, so there should be a cooldown inbetween interacts. Can simply store the timestamp of a rightclick and check at the beginning of the player interact event listener if timestamp+cooldown has passed. Cooldown should be configurable in the config (use Idofront TimeStamp).

**Comment by RuKira** [comment]
@Norazan 

I think this is not an "Easy" issue,

I believe TPS is dropping because is accessing the database every time,
so we would need to implement a feature here that does not involve a database, and cancel the events of the database, and Setting/Removing spawn.

You basically, want to stop the query of the database.

**Comment by Norazan** [comment]
The TPS is indeed dropping because it is accessing the database everytime, but adding a cooldown between interacts (setting/unsetting bonfire respawn) is an easy solution to that. Even if its just one second, that is probably already enough. If you got a bot that clicked once every tick, you'd need 20x as many bots and bonfires to achieve the same rate of generating lagg.

**Comment by RuKira** [comment]
Adding onto this, Like I said, 

You are correct, you just need to add a cooldown, but you need to make the cooldown not access the database, meaning it can't be stored except locally, and it needs to still store player data, 
and not interact with the database (cancel the event)

I believe, either way SQL stuff is out of my knowledge.
Sorry, I am sure it's easier than it sounds, but for me, I am not sure.

Going by what Scyu said, more or less.

**Comment by Norazan** [comment]
Yes that is right, the current solution I'm working on stores the cooldown on the Geary component in the PDC.

**Comment by Norazan** [comment]
On hold until https://github.com/MineInAbyss/Geary/issues/40 is resolved
